### ISSUE TITLE
0.05 and 1.1 measurements?

### ISSUE THREAD

**Issue by seenoevo** [rldaulton/connectedness#1]
Hi, can you tell me where you got the 0.05 measurements to 3G network and 1.1 to the equivalent 35 Mbps?

With the default 0.05 set, I see the Mbps output of 0.1754, but speed test shows I have a download speed of 67 Mbps so I'm not sure how to relate the two?

Thanks

**Comment by rldaulton** [comment]
@seenoevo oh wow - I never saw this. Must've missed the notification. Do you still need a Swift 3 Update?

**Comment by uchiha-itachi95** [comment]
I am also facing the same issue. The speed the method is returning is 21Mbps (after multiplying by 8) but internet speed test is showing my speed as 64.3Mpbs. How to get that?
